---
- name: Reload nginx service
  become: true
  ansible.builtin.service:
    name: nginx.service
    enabled: true
    state: restarted
  tags: lighthouse

- name: Start nginx service
  become: true
  ansible.builtin.service:
    name: nginx.service
    enabled: true
    state: restarted
  tags: lighthouse